// Generated by https://quicktype.io

export interface Countries {
     name: Name
     tld?: string[]
     cca2: string
     ccn3?: string
     cca3: string
     cioc?: string
     independent?: boolean
     status: Status
     unMember: boolean
     currencies?: Currencies
     idd: Idd
     capital?: string[]
     altSpellings: string[]
     region: Region
     subregion?: string
     languages?: Languages
     translations: { [key: string]: Translation }
     latlng: number[]
     landlocked: boolean
     borders?: string[]
     area: number
     demonyms?: Demonyms
     flag: string
     maps: Maps
     population: number
     gini?: { [key: string]: number }
     car: Car
     timezones: string[]
     continents: string[]
     flags: CoatOfArms
     coatOfArms: CoatOfArms
     startOfWeek: StartOfWeek
     capitalInfo: CapitalInfo
     postalCode?: PostalCode
     fifa?: string
}

export interface Languages {
     [key: string]: string
}

export interface CapitalInfo {
     latlng?: number[]
}

export interface Car {
     signs?: string[]
     side: Side
}

export enum Side {
     Left = "left",
     Right = "right",
}

export interface CoatOfArms {
     png?: string
     svg?: string
}

export interface Currencies {
     [key: string]: TartuGecko
}

export interface TartuGecko {
     name: string
     symbol: string
}

export interface BAM {
     name: string
}

export interface Demonyms {
     eng: Eng
     fra?: Eng
}

export interface Eng {
     f: string
     m: string
}

export interface Idd {
     root?: string
     suffixes?: string[]
}

export interface Maps {
     googleMaps: string
     openStreetMaps: string
}

export interface Name {
     common: string
     official: string
     nativeName?: NativeName
}

export interface NativeName {
     [key: string]: Translation
}

export interface Translation {
     official: string
     common: string
}

export interface PostalCode {
     format: string
     regex?: string
}

export enum Region {
     Africa = "Africa",
     Americas = "Americas",
     Antarctic = "Antarctic",
     Asia = "Asia",
     Europe = "Europe",
     Oceania = "Oceania",
}

export enum StartOfWeek {
     Monday = "monday",
     Saturday = "saturday",
     Sunday = "sunday",
}

export enum Status {
     OfficiallyAssigned = "officially-assigned",
     UserAssigned = "user-assigned",
}
